version: '3'

networks:
  caddy-cni:
    name: caddy-cni
    driver: bridge
  nginx-cni:
    name: nginx-cni
    driver: bridge

volumes:
  adminer-csi:
    name: adminer-csi
    driver: local

services:
  caddy:
    init: true
    image: docker.io/library/caddy:2-alpine
    container_name: caddy
    networks:
      - caddy-cni
    ports:
      - 8090:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/conf.d:/etc/caddy/conf.d:ro
    volumes_from:
      - adminer:ro
  nginx:
    init: true
    image: docker.io/library/nginx:stable-alpine
    container_name: nginx
    networks:
      - nginx-cni
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - adminer:ro
  adminer:
    init: true
    image: docker.io/library/adminer:fastcgi
    container_name: adminer
    networks:
      - caddy-cni
      - nginx-cni
    volumes:
      - adminer-csi:/var/www/html:ro
