version: '3'

networks:
  nginx-cni:
    name: nginx-cni
    driver: bridge
    external: true

volumes:
  adminer-csi:
    name: adminer-csi
    driver: local

services:
  nginx:
    init: true
    image: docker.io/library/nginx:stable-alpine
    container_name: nginx
    networks:
      - nginx-cni
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - adminer:ro

  adminer:
    init: true
    image: docker.io/library/adminer:fastcgi
    container_name: adminer
    networks:
      - nginx-cni
    volumes:
      - adminer-csi:/var/www/html:ro
